import { Artifact, ExportOptions } from '../types';
import jsPDF from 'jspdf';
import { Octokit } from '@octokit/rest';

// PDF Export
export async function exportToPDF(
  artifact: Artifact,
  options: ExportOptions = { format: 'pdf' }
): Promise<Blob> {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;

  // Title
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text(artifact.title, margin, margin);

  // Metadata
  if (options.includeMetadata) {
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Type: ${artifact.type}`, margin, margin + 10);
    pdf.text(
      `Created: ${new Date(artifact.createdAt).toLocaleString()}`,
      margin,
      margin + 15
    );
    if (artifact.language) {
      pdf.text(`Language: ${artifact.language}`, margin, margin + 20);
    }
  }

  // Content
  pdf.setFontSize(10);
  pdf.setFont('courier', 'normal');

  const lines = pdf.splitTextToSize(artifact.content, maxWidth);
  let y = margin + (options.includeMetadata ? 30 : 15);

  lines.forEach((line: string) => {
    if (y > pageHeight - margin) {
      pdf.addPage();
      y = margin;
    }
    pdf.text(line, margin, y);
    y += 5;
  });

  return pdf.output('blob');
}

// CodeSandbox Export
export async function exportToCodeSandbox(artifact: Artifact): Promise<string> {
  const parameters = {
    files: {
      'package.json': {
        content: JSON.stringify({
          name: artifact.title.toLowerCase().replace(/\s+/g, '-'),
          version: '1.0.0',
          description: `Generated from C1 AI Agent - ${artifact.title}`,
          main: 'index.js',
          dependencies:
            artifact.type === 'react'
              ? {
                  react: '^18.0.0',
                  'react-dom': '^18.0.0',
                }
              : {},
        }),
      },
      'index.js': {
        content: artifact.content,
      },
      'README.md': {
        content: `# ${artifact.title}\n\nGenerated from C1 AI Agent\n\nType: ${artifact.type}\nLanguage: ${artifact.language || 'JavaScript'}\n`,
      },
    },
  };

  const compressed = btoa(JSON.stringify(parameters));
  const url = `https://codesandbox.io/api/v1/sandboxes/define?parameters=${compressed}`;

  return url;
}

// GitHub Gist Export
export async function exportToGist(
  artifact: Artifact,
  githubToken?: string
): Promise<string> {
  if (!githubToken) {
    throw new Error('GitHub token is required for Gist export');
  }

  const octokit = new Octokit({
    auth: githubToken,
  });

  const fileExtension = getFileExtension(artifact.type, artifact.language);
  const fileName = `${artifact.title.replace(/\s+/g, '-')}.${fileExtension}`;

  try {
    const response = await octokit.gists.create({
      description: `${artifact.title} - Generated from C1 AI Agent`,
      public: false,
      files: {
        [fileName]: {
          content: artifact.content,
        },
        'README.md': {
          content: `# ${artifact.title}\n\n**Type:** ${artifact.type}\n**Language:** ${artifact.language || 'N/A'}\n**Created:** ${new Date(artifact.createdAt).toLocaleString()}\n**Version:** ${artifact.version}\n\nGenerated by C1 AI Agent`,
        },
      },
    });

    if (!response.data.html_url) {
      throw new Error('No Gist URL returned');
    }

    return response.data.html_url;
  } catch (error) {
    console.error('Failed to create Gist:', error);
    throw new Error('Failed to create GitHub Gist');
  }
}

// Download as file
export function downloadArtifact(artifact: Artifact): void {
  const fileExtension = getFileExtension(artifact.type, artifact.language);
  const fileName = `${artifact.title.replace(/\s+/g, '-')}.${fileExtension}`;

  const blob = new Blob([artifact.content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Export to JSON
export function exportToJSON(artifact: Artifact): string {
  return JSON.stringify(artifact, null, 2);
}

// Helper function to get file extension
function getFileExtension(
  type: string,
  language?: string
): string {
  if (language) {
    const extensions: Record<string, string> = {
      javascript: 'js',
      typescript: 'ts',
      python: 'py',
      java: 'java',
      cpp: 'cpp',
      c: 'c',
      go: 'go',
      rust: 'rs',
      ruby: 'rb',
      php: 'php',
      swift: 'swift',
      kotlin: 'kt',
      jsx: 'jsx',
      tsx: 'tsx',
      html: 'html',
      css: 'css',
      sql: 'sql',
      json: 'json',
      yaml: 'yaml',
      xml: 'xml',
      mermaid: 'mmd',
    };
    return extensions[language.toLowerCase()] || 'txt';
  }

  const typeExtensions: Record<string, string> = {
    code: 'txt',
    markdown: 'md',
    mermaid: 'mmd',
    react: 'jsx',
    html: 'html',
    sql: 'sql',
    chart: 'json',
    'data-viz': 'json',
  };

  return typeExtensions[type] || 'txt';
}
